# Generated by Django 5.1.4 on 2024-12-19 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('qualification', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('hobby', models.CharField(max_length=50)),
                ('annual_income', models.IntegerField()),
                ('languages', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='User_Images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
