# Generated by Django 5.1.3 on 2024-12-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
