# Generated by Django 5.1.4 on 2024-12-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
