# Generated by Django 5.1.4 on 2024-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0002_alter_register_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='annual_income',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
