# Generated by Django 5.1.4 on 2024-12-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0003_alter_register_annual_income_alter_register_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='annual_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.BigIntegerField(default=1010101010),
        ),
        migrations.AlterField(
            model_name='register',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
