# Generated by Django 5.1.4 on 2024-12-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0004_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='register',
            name='first_name',
            field=models.CharField(default='user', max_length=15),
        ),
        migrations.AddField(
            model_name='register',
            name='phonenumber',
            field=models.BigIntegerField(default=1123),
        ),
    ]
