# Generated by Django 5.1.4 on 2024-12-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0005_register_email_register_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='about',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='annual_income',
            field=models.IntegerField(default='100000'),
        ),
        migrations.AddField(
            model_name='register',
            name='birth_date',
            field=models.DateField(default='01-01-2001'),
        ),
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='country',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='register',
            name='hobbies',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='images',
            field=models.ImageField(default='Not Specified', upload_to='User_Images/'),
        ),
        migrations.AddField(
            model_name='register',
            name='landmark',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='languages',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='pincode',
            field=models.IntegerField(default='100000'),
        ),
        migrations.AddField(
            model_name='register',
            name='qualification',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='state',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
    ]
