# Generated by Django 5.1.4 on 2024-12-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0006_register_about_register_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birth_date',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
