# # Generated by Django 5.1.4 on 2024-12-18 10:23

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('nass', '0007_alter_register_birth_date'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='register',
#             name='birth_date',
#             field=models.DateField(default='2001-01-01'),
#         ),
#     ]
from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0007_alter_register_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birth_date',
            field=models.DateField(default=date(2001, 1, 1)),  # Use a datetime.date object
        ),
    ]
