# Generated by Django 5.1.4 on 2024-12-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0008_alter_register_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='hobbies',
            new_name='hobby',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
