# Generated by Django 5.1.4 on 2024-12-18 16:38
from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0009_rename_hobbies_register_hobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birth_date',
            field=models.DateField(default=date(2001, 1, 1)),
        ),
    ]
