# Generated by Django 5.1.3 on 2024-12-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0012_alter_register_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='images',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='User_Images/'),
        ),
    ]
